server:
  port: 18899
spring:
  application:
    name: fire-app-api
  http:
    encoding:
      charset: utf-8
      force: true
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: gz
    password: gaozhan123
    url: jdbc:mysql://118.25.40.121:3306/fire?useUnicode=true&useSSL=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 from dual
mybatis:
  mapper-locations: classpath:com.fire.communication.app.biz.mapper/*.xml
  configuration.map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
  before: true